### ISSUE TITLE
Syntax error in example causing EMR Bootstrap to fail

### ISSUE THREAD

**Issue by davidshere** [Yelp/mrjob#1516]
I'm trying to run an mrjob script on EMR, and it's failing as the cluster opens, when the contents of mrjob are compiled.

The failure is happening because of a syntax error in one of the included examples, mr_spark_wordcount_mrjob.py. 

Here is the error, as suggested by mrjob:
```
+ sudo python3 -m compileall -q -f /usr/lib/python3.4/dist-packages/mrjob
*** Error compiling '/usr/lib/python3.4/dist-packages/mrjob/examples/mr_spark_wordcount_mrjob.py'...
  File "/usr/lib/python3.4/dist-packages/mrjob/examples/mr_spark_wordcount_mrjob.py", line 39
    .map(lambda (word, count): protocol.write(word, count))
                ^
SyntaxError: invalid syntax
```

This makes sense, the syntax should be:
```.map(lambda word, count: protocol.write(word, count))```

This file isn't a part of the mrjob repo, either the master or spark branches. Can it be removed from the distribution used by EMR? Is there some setting I'm not setting?

**Comment by davidmarin** [comment]
Oh shoot, that must have gotten into the distribution on PyPI by mistake. Yes, I'll look into this and fix it.

**Comment by davidmarin** [comment]
This seems to affect the wheel but not the tarball.

I'll see if I can find a clever way to rebuild the wheel file without having to create a new release on PyPI.

**Comment by davidshere** [comment]
Really appreciate the prompt assistance.

**Comment by davidmarin** [comment]
Sure. :)

Okay, it looks like I can fix this by building separate py2 and py3 wheels, and then deleting the `py2.py3` wheel file.

Unfortunately, I'm out of time for today, but I'll try to get to this tomorrow.

**Comment by davidmarin** [comment]
This should be fixed on PyPI.

**Comment by davidshere** [comment]
Thanks David, I'm still getting the error. Is it possible I'm doing something wrong on my end that would be causing this?

**Comment by davidmarin** [comment]
Did you re-install mrjob 0.5.7?

**Comment by davidshere** [comment]
Hah, that did it. Thank you very much.
